# Dependabot configuration for automated dependency updates
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 10
    # Group dependency updates to reduce PR noise
    groups:
      # Group all production dependencies
      production-dependencies:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      # Group all development dependencies
      development-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      # Group major version updates separately
      major-updates:
        update-types:
          - 'major'
    # Ignore specific dependencies if needed
    ignore:
      # Example: Don't update to Next.js 16 until ready
      # - dependency-name: "next"
      #   versions: ["16.x"]
    # Add assignees to PRs
    assignees:
      - 'TortoiseWolfe'
    # Add labels to PRs
    labels:
      - 'dependencies'
      - 'automated'
    # Commit message prefix
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 5
    groups:
      # Group all GitHub Actions updates
      github-actions:
        patterns:
          - '*'
    labels:
      - 'github-actions'
      - 'automated'
    commit-message:
      prefix: 'ci'
      include: 'scope'

  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 5
    labels:
      - 'docker'
      - 'automated'
    commit-message:
      prefix: 'build'
      include: 'scope'
