// Auto-generated by detect-project.js
// DO NOT EDIT MANUALLY - This file is regenerated on each build

export const detectedConfig = {
  "projectName": "ScriptHammer",
  "projectOwner": "TortoiseWolfe",
  "projectHost": "github.com",
  "projectUrl": "https://github.com/TortoiseWolfe/ScriptHammer",
  "basePath": "",
  "isGitHub": true,
  "detectionSource": "env",
  "generatedAt": "2025-09-27T23:06:33.187Z"
} as const;

export type DetectedConfig = typeof detectedConfig;
