/**
 * The pre-push validation build must not rewrite the tracked manifest (#1114).
 *
 * WHAT WENT WRONG. `public/manifest.json` is tracked on purpose (#392) so its paths are
 * reviewable. `.husky/pre-push` runs `scripts/validate-ci.sh`, which runs a production build
 * in the `builder` container; that container takes `env_file: .env` and so inherits
 * `NEXT_PUBLIC_BASE_PATH`. For a custom-domain deploy that differs from what the site
 * actually serves, so the generator rewrote `start_url`, `scope` and every icon path in a
 * tracked file — on EVERY push.
 *
 * Observed five times in one session. Each time it was caught only because someone read
 * `gh pr create`'s "1 uncommitted change" warning. Attention is not a mechanism, and
 * committing it ships a manifest that breaks PWA install and offline.
 *
 * WHY THE FIX IS HERE AND NOT IN THE GENERATOR. The first attempt taught
 * `generate-manifest.js` to refuse when the build's base path diverged from the deployed one.
 * That broke the rebrand harness, and correctly so: a rebrand LEGITIMATELY regenerates this
 * file with a diverging base path, which is the whole point of #985 —
 * `tests/rebrand/test-rebrand.sh` asserts a fork gets `/widget-works/`. The generator cannot
 * distinguish an intentional regeneration from an accidental one; the CALLER can, and the
 * pre-push gate knows it only needs the build to succeed.
 *
 * `MANIFEST_OUTPUT_DIR` is the existing seam, added by #931 for this exact class.
 *
 * IT WAS A CLASS, NOT ONE ARTIFACT (#1171). `prebuild` also runs `generate-sitemap.js`,
 * which writes the equally-tracked `public/robots.txt` with a `Sitemap:` line derived from
 * `NEXT_PUBLIC_DEPLOY_URL`. A worktree provisioned from `.env.example` does not set that, so
 * the line fell back to a `github.io` origin (#504) and every validation build dirtied the
 * tree — exactly the same failure, one artifact over, still live for seven weeks after the
 * manifest half was fixed.
 *
 * It survived because this guard named ONE variable. So the table below is the unit now:
 * adding a generated-and-tracked artifact means adding a row, and forgetting the seam fails
 * here rather than in somebody's `git status`.
 */

'use strict';

const { describe, it } = require('node:test');
const assert = require('node:assert');
const path = require('node:path');
const fs = require('node:fs');

const SCRIPT = path.resolve(__dirname, '..', 'validate-ci.sh');

/** The build lines, with shell comments removed so this cannot match its own rationale. */
function buildLines() {
  return fs
    .readFileSync(SCRIPT, 'utf8')
    .split('\n')
    .filter((l) => !l.trim().startsWith('#'))
    .filter((l) => /Production build/.test(l));
}

/**
 * Every artifact that is BOTH generated by `prebuild` and tracked in git.
 *
 * A row here is the whole contract: the caller must redirect `env`, and the generator must
 * still read it. Both halves are asserted below, because either one alone passes while the
 * tree still gets dirtied.
 */
const ARTIFACTS = [
  {
    env: 'MANIFEST_OUTPUT_DIR',
    generator: 'generate-manifest.js',
    artifact: 'public/manifest.json',
    issue: '#1114',
    breaks: 'a manifest that breaks PWA install and offline',
  },
  {
    env: 'ROBOTS_OUTPUT_DIR',
    generator: 'generate-sitemap.js',
    artifact: 'public/robots.txt',
    issue: '#1171',
    breaks:
      'a robots.txt advertising a github.io sitemap instead of the real origin',
  },
];

describe('pre-push validation build writes tracked artifacts to scratch (#1114, #1171)', () => {
  it('finds the production-build invocations, so the check is not vacuous', () => {
    const lines = buildLines();
    assert.ok(
      lines.length >= 2,
      `expected both the in-container and host-Docker build lines, found ${lines.length}. ` +
        'If validate-ci.sh was restructured, re-point this guard rather than deleting it.'
    );
  });

  for (const a of ARTIFACTS) {
    it(`every production build redirects ${a.env}`, () => {
      const offenders = buildLines().filter((l) => !l.includes(a.env));
      assert.deepStrictEqual(
        offenders,
        [],
        `A production build in the pre-push gate does not set ${a.env}, so it will ` +
          `rewrite the tracked ${a.artifact} and leave the tree dirty on every push ` +
          `(${a.issue}). Committing that ships ${a.breaks}.\n\n` +
          `Offending line(s):\n  ${offenders.join('\n  ')}`
      );
    });
  }

  it('the in-container build applies the variable, not merely mentions it (#1127)', () => {
    // THE DEFECT THIS REPLACES. The first version asserted only that the string
    // MANIFEST_OUTPUT_DIR appeared on each build line. It did — on a line reading
    // `MANIFEST_OUTPUT_DIR=/tmp pnpm build`, handed to run_check, which executes its
    // argument as `$command` UNQUOTED. Word-splitting does not perform assignments, so bash
    // tries to run a program literally named `MANIFEST_OUTPUT_DIR=/tmp`. The guard was green
    // over a line that could not work.
    //
    // It went unnoticed because the branch exercised on this machine is the OTHER one —
    // `docker compose run -e`, which is correct. A guard has to cover the branch nobody runs.
    const line = buildLines().find((l) => !l.includes('docker compose'));
    assert.ok(
      line,
      'the in-container build line is gone — re-point this guard'
    );
    for (const a of ARTIFACTS) {
      // Allow any number of OTHER assignments between `env` and this one, so adding a
      // second variable cannot red the first's guard purely by sitting in front of it.
      // What matters is that `env` leads the line — that is what survives word-splitting.
      assert.match(
        line,
        new RegExp(`\\benv\\s+(?:[A-Z_]+=\\S+\\s+)*${a.env}=`),
        `The in-container build sets ${a.env} as a bare \`VAR=value\` prefix. ` +
          'run_check runs `$command` unquoted, and word-splitting does not perform ' +
          `assignments — bash would try to execute a command named \`${a.env}=...\`. ` +
          `Use \`env ${a.env}=... <cmd>\`, which is a real program and survives ` +
          `word-splitting.\n\nLine: ${line.trim()}`
      );
    }
  });

  it('demonstrates WHY: word-splitting drops a bare assignment but honours env', () => {
    // The mechanism, driven rather than asserted. If this ever fails, bash changed and the
    // rule above needs revisiting — better that than the rule quietly becoming folklore.
    const { spawnSync } = require('node:child_process');
    const run = (cmd) =>
      spawnSync('bash', ['-c', `c="${cmd}"; $c`], { encoding: 'utf8' });

    const bare = run('PROBE_1127=applied printenv PROBE_1127');
    assert.notStrictEqual(
      bare.status,
      0,
      'a bare VAR=value prefix survived word-splitting — the premise of this guard is wrong'
    );

    const viaEnv = run('env PROBE_1127=applied printenv PROBE_1127');
    assert.strictEqual(viaEnv.stdout.trim(), 'applied');
  });

  for (const a of ARTIFACTS) {
    it(`${a.generator} still honours the seam it depends on`, () => {
      // The guard above is worthless if the variable stops being read. Asserting the
      // generator still implements it keeps the two halves from drifting apart silently —
      // which is the failure mode where a gate keeps passing while the thing it gates is gone.
      const gen = fs.readFileSync(
        path.resolve(__dirname, '..', a.generator),
        'utf8'
      );
      const code = gen
        .replace(/\/\*[\s\S]*?\*\//g, '')
        .replace(/(^|[^:])\/\/.*$/gm, '$1');
      assert.match(
        code,
        new RegExp(`process\\.env\\.${a.env}`),
        `${a.generator} no longer reads ${a.env}, so redirecting it in validate-ci.sh does ` +
          `nothing and the pre-push build is dirtying ${a.artifact} again (#931, ${a.issue}).`
      );
    });
  }

  it('redirecting the seam actually diverts the write, end to end (#1171)', () => {
    // NOT a source match. This runs the real generator in a scratch cwd with the variable
    // set, and asserts the tracked path is left alone — which is the claim the whole file
    // makes. Source-matching alone is how #1127 stayed green over a line that could not run.
    const { spawnSync } = require('node:child_process');
    const os = require('node:os');
    const fixture = fs.mkdtempSync(path.join(os.tmpdir(), 'robots-seam-'));
    try {
      fs.mkdirSync(path.join(fixture, 'public'), { recursive: true });
      fs.mkdirSync(path.join(fixture, 'src', 'lib', 'blog'), {
        recursive: true,
      });
      fs.writeFileSync(
        path.join(fixture, 'src', 'lib', 'blog', 'blog-data.json'),
        '{"posts":[]}'
      );
      // The caller supplies an existing directory, exactly as validate-ci.sh passes /tmp —
      // the seam redirects a write, it does not create a tree.
      const scratch = path.join(fixture, 'scratch');
      fs.mkdirSync(scratch, { recursive: true });
      const res = spawnSync(
        process.execPath,
        [path.resolve(__dirname, '..', 'generate-sitemap.js')],
        {
          cwd: fixture,
          encoding: 'utf8',
          env: { PATH: process.env.PATH, ROBOTS_OUTPUT_DIR: scratch },
        }
      );
      assert.strictEqual(
        res.status,
        0,
        `generator failed, so this proves nothing:\n${res.stderr}`
      );
      assert.ok(
        fs.existsSync(path.join(scratch, 'robots.txt')),
        'ROBOTS_OUTPUT_DIR was set but no robots.txt was written there'
      );
      assert.ok(
        !fs.existsSync(path.join(fixture, 'public', 'robots.txt')),
        'the generator wrote public/robots.txt anyway — the seam does not divert the write, ' +
          'which is the exact state that left every pre-push build dirty (#1171)'
      );
    } finally {
      fs.rmSync(fixture, { recursive: true, force: true });
    }
  });
});
