#!/usr/bin/env bash
#
# Make a git worktree usable with this project's Docker-first workflow (#932).
#
# WHY THIS EXISTS. CLAUDE.md recommends a sibling worktree for parallel work. Out of
# the box that does not start: in a worktree `.git` is a FILE holding a `gitdir:`
# pointer into the parent repository, which lives outside the Compose bind mount. The
# path does not resolve inside the container, husky's `prepare` exits 1 during
# `pnpm install`, and the container crashloops — with nothing in the output naming the
# worktree as the cause.
#
# This writes the three things CLAUDE.md otherwise tells you to arrange by hand:
#
#   1. docker-compose.override.yml mounting the parent .git at the SAME absolute path
#      the pointer names, for every service that runs project code. `builder` needs it
#      too — miss that and the container starts, then the production build in the
#      pre-push gate fails the identical way one step later.
#   2. COMPOSE_PROJECT_NAME, so the worktree's volumes and containers do not collide
#      with the primary checkout's.
#   3. SH_PORT, a free one, so two dev servers can run at once.
#
# It never copies the primary checkout's .env. CLAUDE.md is explicit about that, and
# the reason is that a worktree pointed at the same backend is not an isolated
# environment — it is two agents writing to one database.
#
# Usage:  ./scripts/worktree-setup.sh [--force]
set -euo pipefail

FORCE=false
[ "${1:-}" = "--force" ] && FORCE=true

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# shellcheck source=scripts/lib/compose-service.sh
. "$ROOT/scripts/lib/compose-service.sh"

if [ ! -f "$ROOT/.git" ]; then
    echo "Not a worktree: $ROOT/.git is a directory (or missing)."
    echo "This script is only needed in a worktree created with 'git worktree add'."
    exit 0
fi

# `--git-common-dir` is the parent repository's .git, which is what the pointer in a
# worktree's .git file ultimately resolves through. Resolve it to an absolute path:
# the mount has to name the same path the container will look for.
PARENT_GIT="$(cd "$(git rev-parse --git-common-dir)" && pwd)"
APP_SERVICE="$(compose_service "$ROOT/docker-compose.yml")"
if [ -z "$APP_SERVICE" ]; then
    echo "Could not read the app service from docker-compose.yml." >&2
    exit 1
fi

OVERRIDE="$ROOT/docker-compose.override.yml"
if [ -f "$OVERRIDE" ] && [ "$FORCE" = false ]; then
    echo "docker-compose.override.yml already exists; leaving it alone (--force to rewrite)."
else
    # Every service that runs project code needs the mount, not just the app one.
    SERVICES="$APP_SERVICE builder"
    {
        echo "# GENERATED by scripts/worktree-setup.sh — gitignored, machine-specific."
        echo "#"
        echo "# A worktree's .git is a file pointing at the parent repository, which is"
        echo "# outside the bind mount. Without this the path does not resolve in the"
        echo "# container, husky's prepare fails during pnpm install, and the container"
        echo "# crashloops without saying why (#932)."
        echo "services:"
        for svc in $SERVICES; do
            echo "  ${svc}:"
            echo "    volumes:"
            echo "      - ${PARENT_GIT}:${PARENT_GIT}"
        done
    } > "$OVERRIDE"
    echo "Wrote docker-compose.override.yml  (mounts ${PARENT_GIT})"
fi

# A free port, starting from the convention in CLAUDE.md and stepping past anything
# already listening — including the primary checkout's dev server.
port_free() {
    ! (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null
}
PORT=3002
while ! port_free "$PORT"; do PORT=$((PORT + 1)); done

PROJECT="$(basename "$ROOT" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9_-' '-')"
PROJECT="${PROJECT%-}"

if [ ! -f "$ROOT/.env" ]; then
    if [ -f "$ROOT/.env.example" ]; then
        cp "$ROOT/.env.example" "$ROOT/.env"
        echo "Created .env from .env.example — fill in your own backend keys."
        echo "  DO NOT copy the primary checkout's .env: pointing a second container at"
        echo "  the same backend is two agents writing to one database."
    else
        : > "$ROOT/.env"
    fi
fi

set_env() {
    local key="$1" value="$2"
    if grep -q "^${key}=" "$ROOT/.env" 2>/dev/null; then
        # Written with a temp file rather than sed -i: the value is a path or a port,
        # and sed's delimiter would have to be chosen around it.
        awk -v k="$key" -v v="$value" \
            'BEGIN{FS=OFS="="} $1==k {print k "=" v; next} {print}' \
            "$ROOT/.env" > "$ROOT/.env.tmp"
        mv "$ROOT/.env.tmp" "$ROOT/.env"
    else
        printf '%s=%s\n' "$key" "$value" >> "$ROOT/.env"
    fi
}

set_env COMPOSE_PROJECT_NAME "$PROJECT"
set_env SH_PORT "$PORT"
echo "Set COMPOSE_PROJECT_NAME=${PROJECT} and SH_PORT=${PORT} in .env"

echo
echo "Worktree ready. Start it with:"
echo "  docker compose up -d ${APP_SERVICE}"
echo
echo "Note: Git hooks still do not run in a worktree (#672). Run the equivalent"
echo "checks by hand before committing — formatting, lint, type-check, focused"
echo "tests, and 'gitleaks detect --no-git'. Never use --no-verify to hide a failure."
